### PR TITLE
Added Japanese translation, changed the name of the settings screen, and fixed a bug that caused images to appear in the search bar.

### PR DESCRIPTION
**Pull request by SatoMasahiro2005**
Added Japanese translation and changed the display name of the settings screen from "Plugin background config. background 插件配置" to "background".
image

and... A bug that caused images to appear in the search bar has been **"forcefully"** fixed.
Please help me, as I'm sure this is not the right fix by any means.
[details](https://github.com/shalldie/vscode-background/commit/8e2e412b6ab0c1c2788cdbdd78a3684b439c72f3#comments)
This is my first time sending a pull request, so I apologize if it is rude or incomplete.

translation by deepL

### CODE REVIEW

**Comment by SatoMasahiro2005** [comment]
I think the build will fail because I put the latest version of @types/vscode but didn't change the version of package.json...

**Comment by NoDocCat** [comment]
The config description too long. 
Maybe we should add real i18n support. like: [git-commit-plugin](https://github.com/RedJue/git-commit-plugin)

**Comment by SatoMasahiro2005** [comment]
I added the package.nls.json

**Comment by shalldie** [comment]
`nls` looks great !

A `README Generator` seems to be needed ~
I will study it in detail this weekend.

**Comment by shalldie** [comment]
image

image

I merged into branch [feature-i18n](https://github.com/shalldie/vscode-background/blob/feature-i18n/README.ja-JP.md) and checked, would you like to supplement the translation in these two places?

**Pull request merged**
