### PR TITLE
Added the ability to set home screen background.

### PR DESCRIPTION
**Pull request by Unthrottled**
# Motivation 

Thanks for the awesome plugin, hopefully you think this can make VS-Code even better with this extension.

I added the ability for the users to set a background for the home screen. The window when all the editor tabs are closed.
Peek 2020-07-05 10-46

# Notes

- I tried to follow the code style already in place and made sure to run `npm run fix` before hand.
- I documented the new functionality (and tried to in the code) in English. 虽然我会读和说一点中文, 我不可以帮助 😅 (sorry if that was bad, I'm still learning)
- I thought this would be fun, if you don't want it no big deal. I just thought I would share :)

### CODE REVIEW

**Comment by shalldie** [comment]
So so  good this idea is! 
I like it.

My only point of view is that, can home screen use the first image of `vscode.customImages` ?

Much config may make it complex, for example, there may be `background.style`,  `background.styles`, `background.homeScreen.style` for style...  
So I think use the first image may be a better way.

**Comment by Unthrottled** [comment]
> Much config may make it complex

I understand, I can change it. I thought it would be neat to use an image that was different than the one that appears with the code.

**Comment by Unthrottled** [comment]
Alright I made those changes. I decided to use the first image instead of the first `vscode.customImages`, it was less complex :)

I can change it to the first `vscode.customImages` if that was what you really wanted.

Peek 2020-07-06 05-11

**Comment by shalldie** [comment]
Published.

I made some adjustments, when open empty views(include home screen), the image will show.

See here:

image

image

**Pull request merged**
